# Generated by Django 4.2.1 on 2026-01-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='alocated_amount',
            new_name='allocated_amount',
        ),
    ]
