# Generated by Django 4.2.1 on 2026-01-30 22:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_alocated_amount_category_allocated_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='month',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
