# Generated by Django 4.2.1 on 2026-01-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_category_month_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='monthly_reccurence',
            field=models.BooleanField(default=False),
        ),
    ]
