# Generated by Django 4.2.1 on 2026-02-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_rename_monthly_reccurence_category_is_reccurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
